# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: depth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "redepth.PriceLevel" do
    optional :price, :string, 1
    optional :amount, :string, 2
    optional :order_count, :uint64, 3
  end
  add_message "redepth.Depth" do
    repeated :asks, :message, 1, "redepth.PriceLevel"
    repeated :bids, :message, 2, "redepth.PriceLevel"
    optional :updated_at, :string, 3
  end
end

module Redepth::Proto
  PriceLevel = Google::Protobuf::DescriptorPool.generated_pool.lookup("redepth.PriceLevel").msgclass
  Depth = Google::Protobuf::DescriptorPool.generated_pool.lookup("redepth.Depth").msgclass
end
